/**
 * Representative cities per U.S. state for typeahead (not exhaustive).
 * User-added cities are merged from `city_options` in the database.
 */
export const US_CITIES_BY_STATE: Record<string, string[]> = {
  AL: ["Birmingham", "Montgomery", "Mobile", "Huntsville"],
  AK: ["Anchorage", "Fairbanks", "Juneau"],
  AZ: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"],
  AR: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale"],
  CA: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento", "Oakland", "Fresno", "Long Beach"],
  CO: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
  CT: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
  DE: ["Wilmington", "Dover", "Newark"],
  DC: ["Washington"],
  FL: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Tallahassee", "Fort Lauderdale"],
  GA: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens"],
  HI: ["Honolulu", "Hilo", "Kailua"],
  ID: ["Boise", "Meridian", "Nampa"],
  IL: ["Chicago", "Aurora", "Naperville", "Rockford", "Springfield"],
  IN: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"],
  IA: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City"],
  KS: ["Wichita", "Overland Park", "Kansas City", "Topeka"],
  KY: ["Louisville", "Lexington", "Bowling Green", "Owensboro"],
  LA: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"],
  ME: ["Portland", "Lewiston", "Bangor"],
  MD: ["Baltimore", "Frederick", "Rockville", "Gaithersburg"],
  MA: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
  MI: ["Detroit", "Grand Rapids", "Warren", "Ann Arbor", "Lansing"],
  MN: ["Minneapolis", "Saint Paul", "Rochester", "Duluth"],
  MS: ["Jackson", "Gulfport", "Southaven", "Hattiesburg"],
  MO: ["Kansas City", "Saint Louis", "Springfield", "Columbia"],
  MT: ["Billings", "Missoula", "Great Falls"],
  NE: ["Omaha", "Lincoln", "Bellevue"],
  NV: ["Las Vegas", "Henderson", "Reno", "North Las Vegas"],
  NH: ["Manchester", "Nashua", "Concord"],
  NJ: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"],
  NM: ["Albuquerque", "Las Cruces", "Santa Fe"],
  NY: ["New York", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
  NC: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
  ND: ["Fargo", "Bismarck", "Grand Forks"],
  OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
  OK: ["Oklahoma City", "Tulsa", "Norman"],
  OR: ["Portland", "Salem", "Eugene", "Gresham"],
  PA: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Harrisburg"],
  RI: ["Providence", "Warwick", "Cranston"],
  SC: ["Charleston", "Columbia", "North Charleston", "Greenville"],
  SD: ["Sioux Falls", "Rapid City", "Aberdeen"],
  TN: ["Nashville", "Memphis", "Knoxville", "Chattanooga"],
  TX: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Corpus Christi", "Plano"],
  UT: ["Salt Lake City", "West Valley City", "Provo", "West Jordan"],
  VT: ["Burlington", "South Burlington", "Rutland"],
  VA: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Arlington"],
  WA: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
  WV: ["Charleston", "Huntington", "Morgantown"],
  WI: ["Milwaukee", "Madison", "Green Bay", "Kenosha"],
  WY: ["Cheyenne", "Casper", "Laramie"],
};
